"""외부 API와 UI에 의존하지 않는 도메인 계층."""

from safety_dashboard.domain.enums import (
    ContextStatus,
    DataHealth,
    KmaFailureCategory,
    RiskGrade,
    WeatherLayerKind,
    WarningLevel,
)
from safety_dashboard.domain.models import (
    CctvFeed,
    DashboardSnapshot,
    DashboardSummary,
    DisasterMessage,
    DisasterMessageFeed,
    Facility,
    FacilityRegion,
    GeoPoint,
    KmaFailureDiagnostic,
    NearbyCctv,
    OutgoingTelegramMessage,
    RiskAssessment,
    RiskReason,
    Warning,
    WarningFeed,
    WeatherGridPoint,
    WeatherLayerFeed,
    WeatherObservation,
)
from safety_dashboard.domain.region_resolver import (
    KMA_WARNING_SCOPE_PREFIXES,
    WarningZoneIndex,
    boundary_names_for_warning,
    dominant_warning,
    facility_matches_warning,
    normalize_warning_zone_data,
    warning_level_rank,
    warning_matches_facility,
)

__all__ = [
    "CctvFeed",
    "DashboardSnapshot",
    "DashboardSummary",
    "ContextStatus",
    "DataHealth",
    "DisasterMessage",
    "DisasterMessageFeed",
    "Facility",
    "FacilityRegion",
    "GeoPoint",
    "KMA_WARNING_SCOPE_PREFIXES",
    "KmaFailureCategory",
    "KmaFailureDiagnostic",
    "NearbyCctv",
    "OutgoingTelegramMessage",
    "RiskAssessment",
    "RiskGrade",
    "RiskReason",
    "Warning",
    "WarningFeed",
    "WarningLevel",
    "WarningZoneIndex",
    "WeatherGridPoint",
    "WeatherLayerFeed",
    "WeatherLayerKind",
    "WeatherObservation",
    "boundary_names_for_warning",
    "dominant_warning",
    "facility_matches_warning",
    "normalize_warning_zone_data",
    "warning_level_rank",
    "warning_matches_facility",
]
